version: '3.7'
services:
  nginx:
    build: ./nginx/
    container_name: webserver
    volumes:
      # - type: bind
        # source: ./nginx/nginx.conf
        # target: /etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
      - 3456:3456
  tty-proxy:
    container_name: tty-proxy
    build: ./
    ports:
      - 8080:8080
